### ISSUE TITLE
Will be Python 3.x supported in (near) future?

### ISSUE THREAD

**Issue by TheAngryAvocado** [Hypsurus/weeman#1]

**Comment by Hypsurus** [comment]
Yes, sure. i'm thinking to move weeman to python 3. or creating a new branch

**Comment by TheAngryAvocado** [comment]
Nice to hear that. 

Unfortunatelly, whereas I know Python 3, I have no idea about servers.
I wish I could help with porting your project, I'd love to use it one day.

**Comment by Hypsurus** [comment]
Many people still using Python 2, so I dont think it's necessary..
Anyway, It will not be so hard to port weeman to python 3. :smile:

**Comment by TheAngryAvocado** [comment]
Nice, I'd love to help in any way ^_^

**Comment by Hypsurus** [comment]
Hey, I created python-3 branch,

the branch will get updates every new version.
so it will be the stable branch for python 3 :smile: 

Now we can use weeman with python 3:
https://github.com/Hypsurus/weeman/tree/python-3

**Comment by TheAngryAvocado** [comment]
That's so nice, I am happy you are fast at responses and everything :D 
Did you accidentally deleted the branch? It looks like I can't find it.

**Comment by Hypsurus** [comment]
Sorry about that, I will add bs4 and pusg it again. :smile:

**Comment by TheAngryAvocado** [comment]
Wonderful, feel free to notify me by posting here when it's ready ^^

**Comment by Hypsurus** [comment]
Hey, 

I dont have time to maintain two versions.
You can fork weeman and maintain the python 3 version.. send me an email if you want to help out.

Hope you have a great day :smiley:

**Comment by TheAngryAvocado** [comment]
Hello @Hypsurus,

My email adress is "aavoukatos@yahoo.gr". Could you send me an email?
I'd like to discuss a few things before anything :)

No mater what, keep up the good work! Have a great day.
~TheAngryAvocado

**Comment by Hypsurus** [comment]
Hello @TheAngryAvocado , sorry for the delay :smile:

I will email  you soon!
