### ISSUE TITLE
Password Contains '(' character does not display full output

### ISSUE THREAD

**Issue by keireneckert** [Hypsurus/weeman#15]
Any characters following the '(' character in a password are not captured.

For example if I enter 'password(81241' the output will display as 'password'

See below:

Input
email: test
password: password(password

Output
[22:04:02] email => test
[22:04:02] pass => password

**Comment by Hypsurus** [comment]
Hello @keireneckert  sorry for the dealy.

Weeman is going to re-write in javascript (node.js).
but I will try to work on this bug when I will be on my working computer.

Thank you!
