### ISSUE TITLE
Https url

### ISSUE THREAD

**Issue by mazlumagar** [Hypsurus/weeman#4]
This script cannot work successfully for https site. But great work. Thank you

**Comment by abdesslem** [comment]
It worked for me with https site

**Comment by mazlumagar** [comment]
it does not attract css files. I tried for 3 sites

**Comment by Hypsurus** [comment]
I'm using urllib2 for HTTP/HTTPS.
About the css/js files, yes I know, and I'm working on it for the next release.

Anyway thank you, I will add this to known issues.

**Comment by Hypsurus** [comment]
Hey @mazlumagar the bug has been fixed?,
can you reference me to web page with this issue?

Thanks.

**Comment by its0x08** [comment]
It workd good .. 
I tried icloud.com but it doen't work with icloud.com site :/ 
Give it a try to see what happens in background !
