### ISSUE TITLE
Connected device change from Hostname to Private IP

### ISSUE THREAD

**Issue by kangzhengjustin** [Hypsurus/weeman#7]
Previously (Weeman 1.4) I'm able to see those connected device are registered under their hostname. But for now (Weeman 1.5), the connected devices are no longer show their hostname, they show their private IP address instead.

I've tried to revert back to Weeman 1.4, but still there's no luck, still showing private IP address instead.

Does anyone facing this issue?

**Comment by Hypsurus** [comment]
Hello @kangzhengjustin 

I did a little research for this issue, It's no weeman fault!
if you will edit your /etc/hosts to:

```127.0.0.1 New-Blood.local```

and try to connect 127.0.0.1 you will see New-Blood.local instead of IP address.
hope this will answer your issue!
